### ISSUE TITLE
Module installation not happy with superior NPM version

### ISSUE THREAD

**Issue by antoniobrandao** [Maciek416/gps-distance#3]
I got this message when installing gps-distance. Is it really necessary ?

gps-distance@0.0.3: wanted: {"node":">= 0.10.x","npm":"1.2.x"} (current: {"node":"0.10.33","npm":"2.7.3"})

**Comment by Maciek416** [comment]
Definitely not necessary. Thanks for letting me know! `0.0.4` is out with a fix.

**Comment by antoniobrandao** [comment]
cool thanks
